# automatically generated by the FlatBuffers compiler, do not modify

# namespace: EventCam

import flatbuffers

class Event(object):
    __slots__ = ['_tab']

    # Event
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Event
    def X(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Event
    def Y(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # Event
    def Polarity(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateEvent(builder, x, y, polarity):
    builder.Prep(2, 6)
    builder.Pad(1)
    builder.PrependInt8(polarity)
    builder.PrependUint16(y)
    builder.PrependUint16(x)
    return builder.Offset()
